// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCywz2LsCpjqJe3tfY01HC6rzTIkGY3n00',
    appId: '1:469589574361:web:0a94e68273b6532029f4c8',
    messagingSenderId: '469589574361',
    projectId: 'cmmsplus-73840',
    authDomain: 'cmmsplus-73840.firebaseapp.com',
    storageBucket: 'cmmsplus-73840.appspot.com',
    measurementId: 'G-XG5DJPDL1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFzbwN8WIvzo07DbZVG5WEYS9MV6xUJo0',
    appId: '1:469589574361:android:73b846f36068552e29f4c8',
    messagingSenderId: '469589574361',
    projectId: 'cmmsplus-73840',
    storageBucket: 'cmmsplus-73840.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Hkc8MPR2OE9OT5b90smvo9cTtFuc3mA',
    appId: '1:469589574361:ios:47747aff7773ca5529f4c8',
    messagingSenderId: '469589574361',
    projectId: 'cmmsplus-73840',
    storageBucket: 'cmmsplus-73840.appspot.com',
    iosBundleId: 'com.newgen.cmms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Hkc8MPR2OE9OT5b90smvo9cTtFuc3mA',
    appId: '1:469589574361:ios:6777d4720c632f1829f4c8',
    messagingSenderId: '469589574361',
    projectId: 'cmmsplus-73840',
    storageBucket: 'cmmsplus-73840.appspot.com',
    iosBundleId: 'com.elegant.test.cmms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCywz2LsCpjqJe3tfY01HC6rzTIkGY3n00',
    appId: '1:469589574361:web:93a51d394b18759229f4c8',
    messagingSenderId: '469589574361',
    projectId: 'cmmsplus-73840',
    authDomain: 'cmmsplus-73840.firebaseapp.com',
    storageBucket: 'cmmsplus-73840.appspot.com',
    measurementId: 'G-Q49FCN1MRY',
  );
}
